### ISSUE TITLE
Enum schema fails for names starting lowercase

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#1]
Enum schema fails for names starting lowercase, for example:
```
components:
  schemas:
        patientGender:
          description: "Gender of the patient (codes are according to FHIR R4)"
          type: "string"
          enum:
            - female
            - male
            - unknown
            - other
```
The java file is generated with uppercase `PatientGender` but the actual definition of the enum in the class is lowercase `patientGender` which fails the compilation.
