### ISSUE TITLE
Constraints for arrays with non-object types are not validated

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#103]
The type constraints for the item type is not checked given the schema:
```
    ArraySchema:
      type: array
      items:
        type: integer
        minimum: 5
```
