### ISSUE TITLE
FormatType Mapping does not work for enums

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#113]
Since version 1.1.0, format type mappings for enums no longer work, e.g.
```
    MedicationGroup:
      type: object
      properties:
        name:
          type: string
        kind:
          type: string
          enum:
            - NEW
            - REMOVED
            - SAME_SUBSTANCE
          format: MedicationGroupKind
```
and the format mapping
```
formatTypeMapping {
    formatType = "MedicationGroupKind"
    classType = "com.github.muehmar.gradle.openapi.v1.MedicationGroupKind"
}
```
will still produce the KindEnum in the MedicationGroup DTO.
