### ISSUE TITLE
Validation of list properties only working for required and not nullable properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#174]
With the following schema
```

    IntegerMemberArray:
      type: object
      required:
        - numbers1
        - numbers2
      properties:
        numbers1:
          type: array
          items:
            type: integer
            format: int32
            maximum: 100
          minItems: 3
          maxItems: 5
        numbers2:
          type: array
          items:
            type: integer
            format: int32
            maximum: 100
          nullable: true
          minItems: 3
          maxItems: 5
        numbers3:
          type: array
          items:
            type: integer
            format: int32
            maximum: 100
          minItems: 3
          maxItems: 5
        numbers4:
          type: array
          items:
            type: integer
            format: int32
            maximum: 100
          nullable: true
          minItems: 3
          maxItems: 5
```

The number of items in the array gets validated for each property. The maximum constraint for the integer gets only validated for `numbers1`.
