### ISSUE TITLE
Required additional property is missing in full-builder in case there are no normal required properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#193]
Required additional property is missing in full-builder in case there are no normal required properties.

With the following
```
    User:
      required:
        -  street
      properties:
        name:
          type: string
```
the property street is missing in the full builder.
