### ISSUE TITLE
Validation of non-nullable map items

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#258]
A definition for a map property with non-nullable values:

```
    InlinedMapSchema:
      type: object
      properties:
        map:
          type: object
          additionalProperties:
            type: string
```

is not validated correctly as the map could contain `null` values without any validation error.
