### ISSUE TITLE
Compile error for large integers

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#259]
The following schema:
```
    Article:
      required:
        - gtin
      properties:
        gtin:
          type: integer
          format: int64
          minimum: 1000000000000
          maximum: 9999999999999
          example: 9781234567897
```
creates a DTO which does not compile: error: _integer number too large_. The long literal does not end with an 'L'.
