### ISSUE TITLE
All uppercase properties are not serialized properly

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#272]
A schema with a property whose name is all-uppercase will not get serialized correctly with jackson
```
Role:
  type: object
  properties:
    TC:
      type: string
```
In the resulting JSON it will be `{"tc": "value"}` instead of `{"TC":"value"}`.

**Comment by muehmar** [comment]
This bug was already fixed with version 3.x

**Comment by muehmar** [comment]
This is not fixed completely. Properties do no get serialized correctly if they are required and not nullable. This also includes properties which start with a single lowercase letter:
```
Role:
  type: object
  required:
    - TC
    - dTC
  properties:
    TC:
      type: string
    dTC:
      type: string
```
