### ISSUE TITLE
Inline enum of array does not compile

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#280]
The generated DTO for the schema
```
    InlineEnumArray:
      properties:
        data:
          type: array
          items:
            type: string
            enum:
              - HELLO
              - WORLD
```
does not compile as no enum is generated for the array item.
