### ISSUE TITLE
Support for nullable map values

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#292]
A nullable value type of a map
```
    MapObject:
      type: object
      required:
        - usernamesMap
      properties:
        props:
          additionalProperties:
            type: string
            nullable: true
```
should get wrapped into an optional like it is supported for nullable array items.
