### ISSUE TITLE
Support conversions for mappings of Map classes as additional properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#307]
The following would generate a Map as additional properties.
```
components:
  schemas:
    MapAdditionalProperties:
      type: object
      required:
        - name
      properties:
        name:
          type: string
      additionalProperties:
        type: object
        additionalProperties:
          type: string     
``` 

For this, a class mapping for the string (value class of the map) is not supported with conversion, e.g. the following conversion will lead to a compile time error for the schema above.
```
classMapping {
    fromClass = "String"
    toClass = "com.custom.package.CustomString"
    conversion.fromCustomType = "getValue"
    conversion.toCustomType = "CustomString#fromString"
}
```
