### ISSUE TITLE
Improve Map additional properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#308]
If a map is used as additional properties, e.g.
```
    MapAdditionalProperties:
      type: object
      required:
        - name
      properties:
        name:
          type: string
      additionalProperties:
        type: object
        additionalProperties:
          type: string
```
the generator currently generates it as Map<String, String>. 

This causes some problems, like casting and type checking during runtime. A better approach would be to create an object with additional string properties and use the object as additional property for the MapAdditionalProperties DTO. This is also done for arrays. This would also automatically support conversions for Map additional properties (#307).
