### ISSUE TITLE
Basic Support for XML

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#322]
Since Jackson does also support serialisation and deserialisation of XML and the existing JSON properties are also used by the jackson XmlMapper one could also add some basic support for XML.

The first feature would be to support setting the name for the root XML element. By default, Jackson will use the class name of the DTO for the root element. The openapi specification allows to specify a specific name:
```
components:
  schemas:
    book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
      xml:
        name: "xml-book"
```

should result in 
```
<xml-book>
  <id>0</id>
  <title>string</title>
 <author>string</author>
</xml-book>
```
