### ISSUE TITLE
Support XML property names

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#325]
Support changing XML names of properties:

```
components:
  schemas:
    book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          xml:
            name: "xml-title"
        author:
          type: string
```

This should result in:
```
<book>
  <id>0</id>
  <xml-title>string</xml-title>
  <author>string</author>
</book>
```
