### ISSUE TITLE
Support converting a property to an XML attribute

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#326]
Support the schema definition:
```
book:
  type: object
  properties:
    id:
      type: integer
      xml:
        attribute: true
    title:
      type: string
    author:
      type: string
```

This should result in:
```
<book id="0">
  <title>string</title>
  <author>string</author>
</book>
```
