### ISSUE TITLE
Support wrapped and name XML for array properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#328]
The following
```
    Container:
      properties:
        books:
          type: array
          items:
            type: string
          example:
            - "one"
            - "two"
            - "three"
```
should result in
```
<Container>
  <books>
    <books>a</books>
    <books>b</books>
    <books>c</books>
  </books>
</Container>
```
which is equivalent with
```
    Container:
      properties:
        books:
          type: array
          items:
            type: string
         xml
           wrapped: true
          example:
            - "one"
            - "two"
            - "three"
```

Changing the name of the wrapper element as well as the item should be possible with
```
    Container:
      properties:
        books:
          type: array
          items:
            type: string
            xml:
             name: item
         xml
           wrapped: true
           name: book-array
          example:
            - "one"
            - "two"
            - "three"
```
which result in
```
<Container>
  <book-array>
    <item>a</item>
    <item>b</item>
    <item>c</item>
  </book-array>
</Container>
```
