### ISSUE TITLE
additionalProperties for object is not supported in combination with properties

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#42]
In case properties are defined for an object type, additionalProperties are currently ignored.

```
Example:
  type: object
  properties:
    name:
      type: string
  additionalProperties:
    type: string
```
Either support it or list them under the known limitations.
