### ISSUE TITLE
No DTOs with reserved Java Keywords

### ISSUE THREAD

**Issue by 0xCA5A** [muehmar/gradle-openapi-schema#72]
The generator does not support properties named as reserved Java Keywords.

Does not work:
```
    FancyObject:
      required:
        - new
      properties:
        new:
          type: string
        old:
          type: string
```

Does work:
```
    FancyObject:
      required:
        - new2
      properties:
        new:
          type: string
        old:
          type: string
```
