### ISSUE TITLE
Generator does not complain about undefined 'required' properties

### ISSUE THREAD

**Issue by 0xCA5A** [muehmar/gradle-openapi-schema#73]
The generator does not complain here:
```
    FancyObject:
      required:
        - new2
        - next
      properties:
        next:
          type: string
        old:
          type: string
```

Is this more a validation issue... ?
