### ISSUE TITLE
Support Root Map Schemas

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#80]
Root Map Schemas, e.g.

```
    RootMapSchema:
      type: object
      additionalProperties:
        type: object
        required:
          - name
        properties:
          name:
            type: string
          description:
            type: string
```
are currently not supported by the plugin. Inlined Map schemas are working.
