### ISSUE TITLE
PropertyCount constraints are not checked for maps

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#84]
PropertyCount constraints are not checked for maps as properties of objects, e.g. no annotations are generated for:
```
    InlinedMapSchema:
      type: object
      properties:
        map:
          type: object
          minProperties: 2
          maxProperties: 3
          additionalProperties:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              description:
                type: string
```
