### ISSUE TITLE
Add builder for Array-Pojos

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#93]
Add for Array Pojos, e.g.

```
    Array:
      type: array
      maxItems: 4
      items:
        type: number
        format: double
```
a builder. Currently, only a constructor exists.

The builder could provide a method to set a list as well a method to add single items.
