### ISSUE TITLE
Add builder for Map-Pojos

### ISSUE THREAD

**Issue by muehmar** [muehmar/gradle-openapi-schema#94]
Add a builder for Map schemas, e.g.
```
    RootMapSchema:
      type: object
      additionalProperties:
        type: object
        required:
          - name
        properties:
          name:
            type: string
          description:
            type: string
```
Currently, only a constructor exists.

The builder should respect required properties, i.e. like for object pojos, all required properties must be initialized. In the optional part, methods exists for adding properties or set directly the additional properties via Map.
